export const PARENT_COLUMNS = [
  "Type",
  "SKU",
  "Name",
  "Description",
  "Short description",
  "Categories",
  "Images",
  "Attribute 1 name",
  "Attribute 1 value(s)",
  "Bullet Point 1",
  "Bullet Point 2",
  "Bullet Point 3",
  "Bullet Point 4",
  "Bullet Point 5",
  "Search Keywords",
  "Installation Guide/Manual PDF",
  "Line Drawing PDF",
  "Measurement Guide PDF",
  "Warranty PDF",
  "vva_attributes_json",
  "vva_default_formula",
  "vva_default_sku_template",
] as const;

export const CHILD_COLUMNS = [
  "Type",
  "Parent SKU",
  "SKU",
  "Name",
  "Regular price",
  "Images",
  "Woo Variation Gallery Images",
  "Attribute 1 name",
  "Attribute 1 value(s)",
  "Package Weight",
  "Package Weight Unit",
  "Items per Inner Pack",
  "Number of Boxes",
  "vva_values_json",
] as const;

export const FAILURE_COLUMNS = ["URL", "Reason", "Missing Fields"] as const;

export const CHILD_IMAGE_INDEXES: Array<number | null> = [
  null,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
];
